<?php

namespace Snoke\WsBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('snoke_ws');
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('mode')->defaultValue('terminator')->end()
                ->arrayNode('transport')
                    ->children()
                        ->scalarNode('type')->defaultNull()->end()
                        ->arrayNode('http')
                            ->children()
                                ->scalarNode('base_url')->isRequired()->end()
                                ->scalarNode('publish_path')->defaultValue('/internal/publish')->end()
                                ->integerNode('timeout_seconds')->defaultValue(5)->end()
                                ->arrayNode('auth')
                                    ->children()
                                        ->enumNode('type')->values(['api_key', 'none'])->defaultValue('api_key')->end()
                                        ->scalarNode('header')->defaultValue('X-Api-Key')->end()
                                        ->scalarNode('value')->defaultValue('')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('redis_stream')
                            ->children()
                                ->scalarNode('dsn')->defaultValue('redis://redis:6379')->end()
                                ->scalarNode('stream')->defaultValue('ws.outbox')->end()
                                ->scalarNode('group')->defaultValue('ws-gateway')->end()
                                ->scalarNode('consumer')->defaultValue('symfony')->end()
                            ->end()
                        ->end()
                        ->arrayNode('rabbitmq')
                            ->children()
                                ->scalarNode('dsn')->defaultValue('amqp://guest:guest@rabbitmq:5672/')->end()
                                ->scalarNode('exchange')->defaultValue('ws.outbox')->end()
                                ->scalarNode('queue')->defaultValue('ws.outbox')->end()
                                ->scalarNode('routing_key')->defaultValue('ws.outbox')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('presence')
                    ->children()
                        ->scalarNode('type')->defaultNull()->end()
                        ->arrayNode('http')
                            ->children()
                                ->scalarNode('base_url')->isRequired()->end()
                                ->scalarNode('list_path')->defaultValue('/internal/connections')->end()
                                ->scalarNode('by_user_path')->defaultValue('/internal/users/{user_id}/connections')->end()
                                ->integerNode('timeout_seconds')->defaultValue(5)->end()
                            ->end()
                        ->end()
                        ->arrayNode('redis')
                            ->children()
                                ->scalarNode('dsn')->defaultValue('redis://redis:6379')->end()
                                ->scalarNode('prefix')->defaultValue('presence:')->end()
                                ->integerNode('ttl_seconds')->defaultValue(120)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('events')
                    ->children()
                        ->scalarNode('type')->defaultNull()->end()
                        ->arrayNode('webhook')
                            ->children()
                                ->scalarNode('path')->defaultValue('/internal/ws/events')->end()
                                ->booleanNode('enabled')->defaultValue(true)->end()
                            ->end()
                        ->end()
                        ->arrayNode('redis_stream')
                            ->children()
                                ->scalarNode('dsn')->defaultValue('redis://redis:6379')->end()
                                ->scalarNode('stream')->defaultValue('ws.events')->end()
                                ->scalarNode('group')->defaultValue('symfony')->end()
                                ->scalarNode('consumer')->defaultValue('symfony')->end()
                            ->end()
                        ->end()
                        ->arrayNode('rabbitmq')
                            ->children()
                                ->scalarNode('dsn')->defaultValue('amqp://guest:guest@rabbitmq:5672/')->end()
                                ->scalarNode('exchange')->defaultValue('ws.events')->end()
                                ->scalarNode('queue')->defaultValue('ws.events')->end()
                                ->scalarNode('routing_key')->defaultValue('ws.events')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('subjects')
                    ->children()
                        ->scalarNode('user_prefix')->defaultValue('user:')->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
